# Generated by Django 5.1.3 on 2024-12-07 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quewstion_text',
            new_name='question_text',
        ),
    ]
